name: Publish Metadata to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
     contents: write
     pages: write
     pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install markdown pyaml pillow requests

      - name: Extract Metadata
        run: |
          mkdir -p output
          python .github/extract_metadata.py "https://esa-eodash.github.io/eodashboard-narratives/"
          cp *.md output
          touch output/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4
        with:
          folder: ./output
          branch: gh-pages
          clean-exclude: pr-preview
          force: false